### PR TITLE
Enhancement: 51 stats option for line bar charts

### PR DESCRIPTION
**Pull request by RdeLange**
Addressing #51 
.... and as a bonus fix the buggy Also Include and make the Also Include persistent

Testing:

**Statistics**
- go to the dashboard tab
- create a bar/line widget
- in the widget options (right bottom corner) choose Stats
- pick a specific statistic
=> the statistic should be visible as a blue line in the chart
- switch Nomie tabs or restart Nomie app
- go to the dashboard tab
=> the statistics should persist on the dashboard
- in the widget options (right bottom corner) choose Stats
- pick No Stats
=> the blue statistics line should be gone

**Also Include**
- go to the dashboard tab
- create a bar/line widget
- in the widget options (right bottom corner) choose Include
- in the next menu choose Select Trackable
- select the trackable you want to add to the widget
=> the other trackable should be visible in the widget chart
- switch Nomie tabs or restart Nomie app
- go to the dashboard tab
=> the statistics should persist on the dashboard
- in the widget options (right bottom corner) choose Include
- pick No Other Trackable
=> the other trackable should not be visible in the widget anymore

### CODE REVIEW

**Comment by donalmacanri** [comment]
This looks really promising! I will hopefully get some time to dig into it tomorrow.

**Comment by RdeLange** [comment]
I will adjust 1 small thing: the statistics line is having datapoint dots. I don’t like that and it is not needed so I will do a small code update later today

**Comment by RdeLange** [comment]
> 

Done

**Comment by donalmacanri** [comment]
Sorry, it's been a mad week. I will get to this tomorrow, looking forward to it.

**Comment by RdeLange** [comment]
Don’t worry, first things first

**Comment by donalmacanri** [comment]
Features like this remind me that we could really use a good fake data set for testing with. Nevertheless, I managed to test it all with a very small data set on desktop and mobile, and all is well. This is a really useful addition. LGTM!

**Review by donalmacanri — APPROVED** [review]

**Pull request merged**
