### PR TITLE
fix: previous text overwriting capture field when using trackers

### LINKED ISSUE #28: Text of previous entry shows up in "What's Up"-field
I have encountered a bug when I use trackers consecutively. After starting the app, the first note saves correctly. When I then use a second tracker without saving instantly (i.e. a tally tracker with "save on tap" disabled or by pressing "insert" on an input menu), the text that appears in the text field is wrong. Instead of the value of tracker nr. 2, it will show the text of tracker nr. 1, which has already been saved. It seems the app wrongly remembers this text, which I can only clear by restarting the app or switching to another menu tab e.g. History or Dash.

I'm using version 6.1 on my android phone, installed as an app via Chrome.

### PR DESCRIPTION
**Pull request by donalmacanri**
Fixes #28 (I think)

This issue is intermittent and I have had a lot of trouble reproducing it consistently, but it usually happens after saving, and inserting trackers and clicking around a lot over the course of a few minutes. After a lot of tracing, I have identified the apparent source of the issue and I think this PR resolves it.

### CODE REVIEW

**Comment by donalmacanri** [comment]
@c-rohrbach could you try the preview build linked above and see if can reproduce the issue however you were able to before?

**Comment by c-rohrbach** [comment]
Looks good to me, I can't reproduce it anymore on my end!

**Comment by Rolikasi** [comment]
Looks good to me as well. Good job

**Review by RdeLange — APPROVED** [review]
👍

**Pull request merged**
